# Dependencies:
# A storage class named 'standard' should exist
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-clover-pvc
  labels:
    app: jenkins-clover
    project: clover
  namespace: jenkins-clover-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  storageClassName: standard
