apiVersion: v1
data:
  jenkins-admin-password: amVOa2luNU9QTkZWX0NMMFZlNA==
  jenkins-admin-user: YWRtaW4=
kind: Secret
metadata:
  labels:
    app: jenkins
    project: clover
  name: jenkins-clover-secret
  namespace: jenkins-clover-ns
type: Opaque
