apiVersion: v1
kind: Service
metadata:
  name: jenkins-clover-svc-agent
  labels:
    app: jenkins
    project: clover
  namespace: jenkins-clover-ns
spec:
  ports:
  - name: slavelistener
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins
    project: clover
  type: ClusterIP
