---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
  name: redis
spec:
  containers:
    - name: redis
      image: k8s.gcr.io/redis:v1
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
    - name: sentinel
      image: kubernetes/redis:v1
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
  volumes:
    - name: data
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
  selector:
    name: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clover-server1
  labels:
    app: clover-server1
spec:
  template:
    metadata:
      labels:
        app: clover-server1
    spec:
      containers:
        - name: clover-server1
          image: opnfv/clover-ns-nginx-server:latest
          ports:
           - containerPort: 50054
           - containerPort: 9180
---
apiVersion: v1
kind: Service
metadata:
  name: clover-server1
  labels:
    app: clover-server1
spec:
  ports:
  - port: 50054
    name: grpc
  - port: 9180
    name: http
  selector:
    app: clover-server1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clover-server2
  labels:
    app: clover-server2
spec:
  template:
    metadata:
      labels:
        app: clover-server2
    spec:
      containers:
        - name: clover-server2
          image: opnfv/clover-ns-nginx-server:latest
          ports:
           - containerPort: 50054
           - containerPort: 9180
---
apiVersion: v1
kind: Service
metadata:
  name: clover-server2
  labels:
    app: clover-server2
spec:
  ports:
  - port: 50054
    name: grpc
  - port: 9180
    name: http
  selector:
    app: clover-server2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clover-server3
  labels:
    app: clover-server3
spec:
  template:
    metadata:
      labels:
        app: clover-server3
    spec:
      containers:
        - name: clover-server3
          image: opnfv/clover-ns-nginx-server:latest
          ports:
           - containerPort: 50054
           - containerPort: 9180
---
apiVersion: v1
kind: Service
metadata:
  name: clover-server3
  labels:
    app: clover-server3
spec:
  ports:
  - port: 50054
    name: grpc
  - port: 9180
    name: http
  selector:
    app: clover-server3
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clover-server4
  labels:
    app: clover-server4
spec:
  template:
    metadata:
      labels:
        app: clover-server4
    spec:
      containers:
        - name: clover-server4
          image: opnfv/clover-ns-nginx-server:latest
          ports:
           - containerPort: 50054
           - containerPort: 9180
---
apiVersion: v1
kind: Service
metadata:
  name: clover-server4
  labels:
    app: clover-server4
spec:
  ports:
  - port: 50054
    name: grpc
  - port: 9180
    name: http
  selector:
    app: clover-server4
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clover-server5
  labels:
    app: clover-server5
spec:
  template:
    metadata:
      labels:
        app: clover-server5
    spec:
      containers:
        - name: clover-server5
          image: opnfv/clover-ns-nginx-server:latest
          ports:
           - containerPort: 50054
           - containerPort: 9180
---
apiVersion: v1
kind: Service
metadata:
  name: clover-server5
  labels:
    app: clover-server5
spec:
  ports:
  - port: 50054
    name: grpc
  - port: 9180
    name: http
  selector:
    app: clover-server5
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-lb-v1
  labels:
    app: http-lb
    version: v1
spec:
  template:
    metadata:
      labels:
        app: http-lb
        version: v1
    spec:
      containers:
        - name: http-lb
          image: opnfv/clover-ns-nginx-lb:latest
          ports:
           - containerPort: 50054
           - containerPort: 9180
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-lb-v2
  labels:
    app: http-lb
    version: v2
spec:
  template:
    metadata:
      labels:
        app: http-lb
        version: v2
    spec:
      containers:
        - name: http-lb
          image: opnfv/clover-ns-nginx-lb:latest
          ports:
           - containerPort: 50054
           - containerPort: 9180
---
apiVersion: v1
kind: Service
metadata:
  name: http-lb
  labels:
    app: http-lb
spec:
  ports:
  - port: 50054
    name: grpc
  - port: 9180
    name: http
  selector:
    app: http-lb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: snort-ids
  labels:
    app: snort-ids
spec:
  template:
    metadata:
      labels:
        app: snort-ids
    spec:
      containers:
        - name: snort-ids
          image: opnfv/clover-ns-snort-ids:latest
          ports:
           - containerPort: 50052
           - containerPort: 50054
           - containerPort: 6379
           - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: snort-ids
  labels:
    app: snort-ids
spec:
  ports:
  - port: 50052
    name: grpc
  - port: 50054
    name: proxy-access-control
  - port: 6379
    name: redis
  - port: 80
    name: http
  selector:
    app: snort-ids
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy-access-control
  labels:
    app: proxy-access-control
spec:
  template:
    metadata:
      labels:
        app: proxy-access-control
    spec:
      containers:
        - name: proxy-access-control
          image: opnfv/clover-ns-nginx-proxy:latest
          ports:
           - containerPort: 50054
           - containerPort: 9180
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-access-control
  labels:
    app: proxy-access-control
spec:
  ports:
  - port: 50054
    name: grpc
  - port: 9180
    name: http
  selector:
    app: proxy-access-control
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: proxy-gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path:
        backend:
          serviceName: proxy-access-control
          servicePort: 9180
---
#
#
# Right now I embed the cassandra statefulset here but
# The addition below can also be separated into a separate
# yaml file and executed after the invocation of
# the original service_delivery_controller_opnfv.yaml
# by invoking:
#  % kubectl create -f <(istioctl kube-inject --debug -f the_new_yaml_file.yaml)
#
#
#
# Cassandra Statefulset
#
# Assumption:
#    - The Cassandra Statefulset right now assumes that
#    the service is deployed in the 'default' namespace
#    therefore the environment variable CASSANDRA_SEEDS is set to
#    "cassandra-0.cassandra.default.svc.cluster.local" below.
#    if you want to use your own name space other than 'default'
#    the value becomes:
#    "cassandra-0.cassandra.<NAMESPACE_NAME>.svc.cluster.local"
#    note that this value rely on a functioning DNS on kubernetes to resolve the IP
#
#    This static method can be made dynamic by using Helm
#    or bash script to replace the namespace on the fly. 
#
#   - Cassandra launch only 1 replica in the cluster
#     to dynamically scale up or down, you can use:
#     kubectl edit statefulset cassandra
#     and edit the value of the replica key
#
#
#
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
  - port: 9042
  selector:
    app: cassandra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: cassandra
        image: cassandra:3
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
           cpu: "500m"
           memory: 1Gi
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra.default.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "MyCassandraDemo"
          - name: CASSANDRA_DC
            value: "DC1-K8Demo"
          - name: CASSANDRA_RACK
            value: "Rack1-K8Demo"

