---
apiVersion: v1
kind: Service
metadata:
  name: clover-collector
  labels:
    app: clover-collector
  namespace: clover-system
spec:
  ports:
  - port: 50054
    name: grpc
  - port: 6379
    name: redis
  - port: 16686
    name: jaeger
  - port: 9090
    name: prometheus
  - port: 9042
    name: cassandra
  selector:
    app: clover-collector
