---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clover-spark-submit
  namespace: clover-system
  labels:
    app: clover-spark
spec:
  template:
    metadata:
      labels:
        app: clover-spark
    spec:
      containers:
        - name: clover-spark
          image: kube1-node1:5000/clover-spark-submit:monday3
