---
apiVersion: v1
kind: Service
metadata:
  name: clover-controller-internal
  namespace: clover-system
  labels:
    app: clover-controller
spec:
  ports:
  - name: http
    port: 80
  - name: grpc
    port: 50052
  - name: grpc-server
    port: 50054
  - name: redis
    port: 6379
  - name: cassandra
    port: 9042
  selector:
    app: clover-controller
