---
apiVersion: v1
kind: Service
metadata:
  name: clover-controller
  labels:
    app: clover-controller
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 32044
    protocol: TCP
  selector:
    app: clover-controller
