kind: Service
apiVersion: v1
metadata:
  name: clover-controller
  namespace: clover-system
spec:
  selector:
    app: clover-controller
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
