---
apiVersion: v1
kind: Service
metadata:
  name: clover-jmeter-master
  labels:
    app: clover-jmeter-master
spec:
  ports:
  - port: 50054
    name: grpc
  - port: 1099
    name: rmi
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: clover-jmeter-master
