apiVersion: v1
kind: Pod
metadata:
  name: clovisor
  labels:
    app: clovisor
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: clovisor
    image: localhost:5000/clovisor
    securityContext:
      privileged: true
    env:
      - name: MY_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
