apiVersion: v1
kind: Service
metadata:
  name: modsecurity-crs
spec:
  type: NodePort
  ports:
  - port: 80
    name: http-modsecurity-crs
    protocol: TCP
    targetPort: 80
  selector:
    app: modsecurity-crs
