# Dependencies:
# A cluster role named 'cluster-admin' with
# admin privileges. Any cluster role with custom
# permissions can also be used
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clover-jenkins
  labels:
    app: jenkins
    project: clover
  namespace: __NAMESPACE__
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
