apiVersion: v1
data:
  jenkins-admin-password: amVOa2luNU9QTkZWX0NMMFZlNA==
  jenkins-admin-user: YWRtaW4=
kind: Secret
metadata:
  labels:
    app: jenkins
    project: clover
  name: clover-jenkins
  namespace: __NAMESPACE__
type: Opaque
