apiVersion: v1
kind: Service
metadata:
  name: clover-jenkins-agent
  labels:
    app: jenkins
    project: clover
  namespace: __NAMESPACE__
spec:
  ports:
  - name: slavelistener
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins
    project: clover
  type: LoadBalancer
