apiVersion: v1
kind: Service
metadata:
  name: clover-jenkins
  labels:
    app: jenkins
    project: clover
  namespace: __NAMESPACE__
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
    project: clover
  type: LoadBalancer
