---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-proxy
  labels:
    app: http-proxy
spec:
  template:
    metadata:
      labels:
        app: http-proxy
    spec:
      containers:
        - name: http-proxy
          image: localhost:5000/http-proxy
          ports:
           - containerPort: 50054
           - containerPort: 9180
---
apiVersion: v1
kind: Service
metadata:
  name: http-proxy
  labels:
    app: http-proxy
spec:
  ports:
  - port: 50054
    name: grpc
  - port: 9180
    name: http
  selector:
    app: http-proxy
---
